name: Launchpads
version: ${project.version}
main: me.Phoenix.Launchpads
authors: [Phoenix]
description: slime block jump pads
website: https://www.lukecolvin.me
commands:
  Launchpads:
    description: Launchpads command
    aliases: [lps, lpad, paddy]
  Launchpads-reload:
    description: Launchpads reload command
    permission: lps.reload
    permission-message: You do not have access to lps.reload
    aliases: [lpreload, lpr]